### ISSUE TITLE
[suggestion] ID number on title

### ISSUE THREAD

**Issue by FaanMaario** [fuyutsuki/Texter#3]
### 必須項目 (Required items)

* ServerOS:

* PHP version:

* Minecraft version:

* Texter version:

* issue(s): I would like to make a suggestion regarding the ID on the title. It would be nice if this ID could be disabled, not to see it.

**Comment by fuyutsuki** [comment]
Thank you for your report.  
  
At a v2.2.6, ID is displayed only for the current operator and owner of FloatingText.  
Text that is not displayed with ID can be displayed from crfts.json.  
  
I disagree about your proposal.  
Because erasing the ID will make it impossible to erase the text.  
  
But if you want to restrict deleting text, I will consider introducing such features.

**Comment by fuyutsuki** [comment]
@FaanMaario Close this issue if there is no response.

**Comment by FaanMaario** [comment]
Okay then
